package io.github.jwyoon1220.pvm.core.engine

import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Label
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes.*

/**
 * Translates a [BlockScanner.BasicBlock] into a JVM class that implements
 * [BlockBody], using the ASM bytecode library.
 *
 * The generated class has:
 *  - a public no-arg constructor
 *  - a public `execute(CPU, MemoryBus, PortIOService, InterruptService, VmContext)V` method
 *
 * [JitSupport] static helpers are called from the generated bytecode to keep
 * the emitted instruction sequences simple while still letting HotSpot inline
 * and optimise the call sites.
 */
internal class JitBlockCompiler(private val loader: JitClassLoader) {

    // ── JVM internal names ───────────────────────────────────────────────────
    private companion object {
        const val CPU_I  = "io/github/jwyoon1220/pvm/core/cpu/CPU"
        const val MEM_I  = "io/github/jwyoon1220/pvm/core/memory/MemoryBus"
        const val PIO_I  = "io/github/jwyoon1220/pvm/core/io/PortIOService"
        const val INT_I  = "io/github/jwyoon1220/pvm/core/io/InterruptService"
        const val CTX_I  = "io/github/jwyoon1220/pvm/api/VmContext"
        const val BB_I   = "io/github/jwyoon1220/pvm/core/engine/BlockBody"
        const val SUP_I  = "io/github/jwyoon1220/pvm/core/engine/JitSupport"
        const val OBJ_I  = "java/lang/Object"

        const val EXEC_DESC =
            "(L$CPU_I;L$MEM_I;L$PIO_I;L$INT_I;L$CTX_I;)V"

        // local variable slots inside execute()
        const val SL_THIS  = 0
        const val SL_CPU   = 1
        const val SL_MEM   = 2
        const val SL_PORTS = 3
        const val SL_INTS  = 4
        const val SL_CTX   = 5
        // temporaries: slots 6, 7, 8
        const val SL_TMP1  = 6
        const val SL_TMP2  = 7
        const val SL_TMP3  = 8
    }

    private var classSeq = 0

    /**
     * Compiles [block] into a [CompiledBlock] and loads the generated class.
     */
    fun compile(block: BlockScanner.BasicBlock): CompiledBlock {
        val className = "jit/Block_${block.startEip.toString(16).uppercase().padStart(8, '0')}_${classSeq++}"
        val bytes = generateClass(className, block)
        val clazz = loader.define(className, bytes)
        val body  = clazz.getDeclaredConstructor().newInstance() as BlockBody
        return CompiledBlockImpl(block.startEip, block.endEip, body)
    }

    // ── class-level generation ───────────────────────────────────────────────

    private fun generateClass(className: String, block: BlockScanner.BasicBlock): ByteArray {
        // COMPUTE_MAXS only: we skip COMPUTE_FRAMES and instead use class version V7 (Java 7)
        // which does NOT require StackMapTable attributes. This avoids the complexity of
        // manually emitting frames or triggering ASM's getCommonSuperClass for our types.
        val cw = ClassWriter(ClassWriter.COMPUTE_MAXS)
        cw.visit(V1_5, ACC_PUBLIC or ACC_FINAL, className, null, OBJ_I, arrayOf(BB_I))

        // Default constructor
        cw.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null).run {
            visitCode()
            visitVarInsn(ALOAD, 0)
            visitMethodInsn(INVOKESPECIAL, OBJ_I, "<init>", "()V", false)
            visitInsn(RETURN)
            visitMaxs(1, 1)
            visitEnd()
        }

        // execute method — the last insn is always a Terminator that ends with RETURN
        val mv = cw.visitMethod(ACC_PUBLIC or ACC_FINAL, "execute", EXEC_DESC, null, null)
        mv.visitCode()
        for (insn in block.insns) mv.emit(insn)
        // Safety RETURN for blocks whose last instruction is not a terminator (shouldn't happen).
        if (block.insns.isEmpty() || !block.insns.last().isTerminator) {
            mv.visitInsn(RETURN)
        }
        mv.visitMaxs(0, 0)
        mv.visitEnd()

        cw.visitEnd()
        return cw.toByteArray()
    }

    // ── per-instruction emission ─────────────────────────────────────────────

    @Suppress("LongMethod", "CyclomaticComplexMethod")
    private fun MethodVisitor.emit(insn: DecodedInsn) = when (insn) {

        is DecodedInsn.Nop -> Unit

        // ── PUSH / POP ───────────────────────────────────────────────────────

        is DecodedInsn.PushR32 -> {
            // cpu.esp -= 4
            loadCpu(); loadCpu(); invokeGetEsp(); pushInt(4); visitInsn(ISUB)
            visitVarInsn(ISTORE, SL_TMP1)
            loadCpu(); visitVarInsn(ILOAD, SL_TMP1); invokeSetEsp()
            // memory.write32(new_esp, cpu.reg)
            loadMem(); visitVarInsn(ILOAD, SL_TMP1)
            loadCpu(); pushInt(insn.reg); invokeSupportStatic("getReg32", "(L$CPU_I;I)I")
            invokeMem("write32", "(II)V")
        }

        is DecodedInsn.PopR32 -> {
            // val = memory.read32(cpu.esp)
            loadMem(); loadCpu(); invokeGetEsp(); invokeMem("read32", "(I)I")
            visitVarInsn(ISTORE, SL_TMP1)
            // cpu.esp += 4
            loadCpu(); loadCpu(); invokeGetEsp(); pushInt(4); visitInsn(IADD); invokeSetEsp()
            // cpu.reg = val
            loadCpu(); pushInt(insn.reg); visitVarInsn(ILOAD, SL_TMP1)
            invokeSupportStatic("setReg32", "(L$CPU_I;II)V")
        }

        is DecodedInsn.PushImm32 -> {
            loadCpu(); loadCpu(); invokeGetEsp(); pushInt(4); visitInsn(ISUB)
            visitVarInsn(ISTORE, SL_TMP1)
            loadCpu(); visitVarInsn(ILOAD, SL_TMP1); invokeSetEsp()
            loadMem(); visitVarInsn(ILOAD, SL_TMP1); pushInt(insn.imm); invokeMem("write32", "(II)V")
        }

        is DecodedInsn.PushImm8Se -> {
            loadCpu(); loadCpu(); invokeGetEsp(); pushInt(4); visitInsn(ISUB)
            visitVarInsn(ISTORE, SL_TMP1)
            loadCpu(); visitVarInsn(ILOAD, SL_TMP1); invokeSetEsp()
            loadMem(); visitVarInsn(ILOAD, SL_TMP1); pushInt(insn.imm); invokeMem("write32", "(II)V")
        }

        // ── MOV ──────────────────────────────────────────────────────────────

        is DecodedInsn.MovR32Imm32 -> {
            loadCpu(); pushInt(insn.reg); pushInt(insn.imm)
            invokeSupportStatic("setReg32", "(L$CPU_I;II)V")
        }

        is DecodedInsn.MovR16Imm16 -> {
            loadCpu(); pushInt(insn.reg); pushInt(insn.imm)
            invokeSupportStatic("setReg16", "(L$CPU_I;II)V")
        }

        is DecodedInsn.MovR8Imm8 -> {
            loadCpu(); pushInt(insn.reg); pushInt(insn.imm)
            invokeSupportStatic("setReg8", "(L$CPU_I;II)V")
        }

        is DecodedInsn.MovRm32R32 -> {
            // src = cpu.reg[(modRM >> 3) & 7]
            loadCpu(); pushInt((insn.modRM shr 3) and 7)
            invokeSupportStatic("getReg32", "(L$CPU_I;I)I")
            visitVarInsn(ISTORE, SL_TMP1)
            // writeRM32(cpu, mem, modRM, sib, disp, src)
            loadCpu(); loadMem()
            pushInt(insn.modRM); pushInt(insn.sib); pushInt(insn.disp)
            visitVarInsn(ILOAD, SL_TMP1)
            invokeSupportStatic("writeRM32", "(L$CPU_I;L$MEM_I;IIII)V")
        }

        is DecodedInsn.MovR32Rm32 -> {
            // dst = readRM32(cpu, mem, modRM, sib, disp)
            loadCpu(); loadMem(); pushInt(insn.modRM); pushInt(insn.sib); pushInt(insn.disp)
            invokeSupportStatic("readRM32", "(L$CPU_I;L$MEM_I;III)I")
            visitVarInsn(ISTORE, SL_TMP1)
            // cpu.reg[(modRM >> 3) & 7] = dst
            loadCpu(); pushInt((insn.modRM shr 3) and 7); visitVarInsn(ILOAD, SL_TMP1)
            invokeSupportStatic("setReg32", "(L$CPU_I;II)V")
        }

        // ── Arithmetic ───────────────────────────────────────────────────────

        is DecodedInsn.AddRm32R32 -> emitBinOpRm32R32(insn.modRM, insn.sib, insn.disp, add = true, store = true)
        is DecodedInsn.AddR32Rm32 -> emitBinOpR32Rm32(insn.modRM, insn.sib, insn.disp, add = true)
        is DecodedInsn.SubRm32R32 -> emitBinOpRm32R32(insn.modRM, insn.sib, insn.disp, add = false, store = true)
        is DecodedInsn.SubR32Rm32 -> emitBinOpR32Rm32(insn.modRM, insn.sib, insn.disp, add = false)
        is DecodedInsn.CmpRm32R32 -> emitBinOpRm32R32(insn.modRM, insn.sib, insn.disp, add = false, store = false)
        is DecodedInsn.CmpR32Rm32 -> emitBinOpR32Rm32_cmp(insn.modRM, insn.sib, insn.disp)

        is DecodedInsn.IncR32 -> {
            // old = cpu.reg; r = old + 1
            loadCpu(); pushInt(insn.reg); invokeSupportStatic("getReg32", "(L$CPU_I;I)I")
            visitVarInsn(ISTORE, SL_TMP1)   // old
            visitVarInsn(ILOAD, SL_TMP1); pushInt(1); visitInsn(IADD)
            visitVarInsn(ISTORE, SL_TMP2)   // r
            // setIncDecFlags(cpu, r, old, true)
            loadCpu(); visitVarInsn(ILOAD, SL_TMP2); visitVarInsn(ILOAD, SL_TMP1); pushInt(1)
            invokeSupportStatic("setIncDecFlags", "(L$CPU_I;IIZ)V")
            // cpu.reg = r
            loadCpu(); pushInt(insn.reg); visitVarInsn(ILOAD, SL_TMP2)
            invokeSupportStatic("setReg32", "(L$CPU_I;II)V")
        }

        is DecodedInsn.DecR32 -> {
            loadCpu(); pushInt(insn.reg); invokeSupportStatic("getReg32", "(L$CPU_I;I)I")
            visitVarInsn(ISTORE, SL_TMP1)   // old
            visitVarInsn(ILOAD, SL_TMP1); pushInt(1); visitInsn(ISUB)
            visitVarInsn(ISTORE, SL_TMP2)   // r
            loadCpu(); visitVarInsn(ILOAD, SL_TMP2); visitVarInsn(ILOAD, SL_TMP1); pushInt(0)
            invokeSupportStatic("setIncDecFlags", "(L$CPU_I;IIZ)V")
            loadCpu(); pushInt(insn.reg); visitVarInsn(ILOAD, SL_TMP2)
            invokeSupportStatic("setReg32", "(L$CPU_I;II)V")
        }

        is DecodedInsn.Grp1Rm32Imm32 -> {
            loadCpu(); loadMem()
            pushInt(insn.modRM); pushInt(insn.sib); pushInt(insn.disp); pushInt(insn.imm)
            invokeSupportStatic("grp1Rm32Imm", "(L$CPU_I;L$MEM_I;IIII)V")
        }

        is DecodedInsn.Grp1Rm32Imm8 -> {
            loadCpu(); loadMem()
            pushInt(insn.modRM); pushInt(insn.sib); pushInt(insn.disp); pushInt(insn.imm)
            invokeSupportStatic("grp1Rm32Imm", "(L$CPU_I;L$MEM_I;IIII)V")
        }

        // ── Terminators: set EIP then return ─────────────────────────────────

        is DecodedInsn.Jcc -> {
            // if (JitSupport.jccTaken(opcode, cpu.eflags)) cpu.eip = target else cpu.eip = fallThru
            pushInt(insn.opcode)
            loadCpu(); invokeCpu("getEflags", "()I")
            invokeSupportStatic("jccTaken", "(II)Z")
            val takenLabel = Label()
            visitJumpInsn(IFNE, takenLabel)
            // not taken
            loadCpu(); pushInt(insn.fallThruEip); invokeCpu("setEip", "(I)V")
            visitInsn(RETURN)
            visitLabel(takenLabel)
            // taken
            loadCpu(); pushInt(insn.targetEip); invokeCpu("setEip", "(I)V")
            visitInsn(RETURN)
        }

        is DecodedInsn.JmpRel8 -> {
            loadCpu(); pushInt(insn.targetEip); invokeCpu("setEip", "(I)V")
            visitInsn(RETURN)
        }

        is DecodedInsn.JmpRel32 -> {
            loadCpu(); pushInt(insn.targetEip); invokeCpu("setEip", "(I)V")
            visitInsn(RETURN)
        }

        is DecodedInsn.CallRel32 -> {
            // push return address (cpu.eip already = insn.endEip after decode)
            loadCpu(); loadCpu(); invokeGetEsp(); pushInt(4); visitInsn(ISUB)
            visitVarInsn(ISTORE, SL_TMP1)
            loadCpu(); visitVarInsn(ILOAD, SL_TMP1); invokeSetEsp()
            loadMem(); visitVarInsn(ILOAD, SL_TMP1); pushInt(insn.endEip); invokeMem("write32", "(II)V")
            // jump
            loadCpu(); pushInt(insn.targetEip); invokeCpu("setEip", "(I)V")
            visitInsn(RETURN)
        }

        is DecodedInsn.Ret -> {
            // cpu.eip = memory.read32(cpu.esp); cpu.esp += 4
            loadCpu()
            loadMem(); loadCpu(); invokeGetEsp(); invokeMem("read32", "(I)I")
            invokeCpu("setEip", "(I)V")
            loadCpu(); loadCpu(); invokeGetEsp(); pushInt(4); visitInsn(IADD); invokeSetEsp()
            visitInsn(RETURN)
        }

        is DecodedInsn.Hlt -> {
            loadCpu(); pushInt(1); invokeCpu("setHalted", "(Z)V")
            loadCpu(); pushInt(insn.endEip); invokeCpu("setEip", "(I)V")
            visitInsn(RETURN)
        }

        is DecodedInsn.IntInsn -> {
            loadCpu(); loadInterrupts(); loadCtx(); pushInt(insn.vector)
            invokeSupportStatic("dispatchInterrupt", "(L$CPU_I;L$INT_I;L$CTX_I;I)V")
            // set EIP to the byte after the INT instruction (already correct — interpreter advances EIP before dispatch)
            loadCpu(); pushInt(insn.endEip); invokeCpu("setEip", "(I)V")
            visitInsn(RETURN)
        }
    }

    // ── Shared binary-op helpers ─────────────────────────────────────────────

    /**
     * Emit ADD/SUB/CMP rm32, r32.
     * [store] is false for CMP (flags only, no write-back).
     */
    private fun MethodVisitor.emitBinOpRm32R32(
        modRM: Int, sib: Int, disp: Int, add: Boolean, store: Boolean
    ) {
        val ri = (modRM shr 3) and 7
        // src = cpu.reg[ri]
        loadCpu(); pushInt(ri); invokeSupportStatic("getReg32", "(L$CPU_I;I)I")
        visitVarInsn(ISTORE, SL_TMP1)
        // dst = readRM32(...)
        loadCpu(); loadMem(); pushInt(modRM); pushInt(sib); pushInt(disp)
        invokeSupportStatic("readRM32", "(L$CPU_I;L$MEM_I;III)I")
        visitVarInsn(ISTORE, SL_TMP2)
        // r = dst ± src
        visitVarInsn(ILOAD, SL_TMP2); visitVarInsn(ILOAD, SL_TMP1)
        visitInsn(if (add) IADD else ISUB)
        visitVarInsn(ISTORE, SL_TMP3)
        // setArithFlags(cpu, r, dst, src, add)
        loadCpu()
        visitVarInsn(ILOAD, SL_TMP3)
        visitVarInsn(ILOAD, SL_TMP2)
        visitVarInsn(ILOAD, SL_TMP1)
        pushInt(if (add) 1 else 0)
        invokeSupportStatic("setArithFlags", "(L$CPU_I;IIIZ)V")
        // writeRM32 (skipped for CMP)
        if (store) {
            loadCpu(); loadMem(); pushInt(modRM); pushInt(sib); pushInt(disp)
            visitVarInsn(ILOAD, SL_TMP3)
            invokeSupportStatic("writeRM32", "(L$CPU_I;L$MEM_I;IIII)V")
        }
    }

    /** Emit ADD/SUB r32, rm32 (result in register). */
    private fun MethodVisitor.emitBinOpR32Rm32(
        modRM: Int, sib: Int, disp: Int, add: Boolean
    ) {
        val ri = (modRM shr 3) and 7
        // dst = cpu.reg[ri]
        loadCpu(); pushInt(ri); invokeSupportStatic("getReg32", "(L$CPU_I;I)I")
        visitVarInsn(ISTORE, SL_TMP2)
        // src = readRM32(...)
        loadCpu(); loadMem(); pushInt(modRM); pushInt(sib); pushInt(disp)
        invokeSupportStatic("readRM32", "(L$CPU_I;L$MEM_I;III)I")
        visitVarInsn(ISTORE, SL_TMP1)
        // r = dst ± src
        visitVarInsn(ILOAD, SL_TMP2); visitVarInsn(ILOAD, SL_TMP1)
        visitInsn(if (add) IADD else ISUB)
        visitVarInsn(ISTORE, SL_TMP3)
        // setArithFlags
        loadCpu()
        visitVarInsn(ILOAD, SL_TMP3)
        visitVarInsn(ILOAD, SL_TMP2)
        visitVarInsn(ILOAD, SL_TMP1)
        pushInt(if (add) 1 else 0)
        invokeSupportStatic("setArithFlags", "(L$CPU_I;IIIZ)V")
        // cpu.reg[ri] = r
        loadCpu(); pushInt(ri); visitVarInsn(ILOAD, SL_TMP3)
        invokeSupportStatic("setReg32", "(L$CPU_I;II)V")
    }

    /** Emit CMP r32, rm32 (flags only). */
    private fun MethodVisitor.emitBinOpR32Rm32_cmp(modRM: Int, sib: Int, disp: Int) {
        val ri = (modRM shr 3) and 7
        loadCpu(); pushInt(ri); invokeSupportStatic("getReg32", "(L$CPU_I;I)I")
        visitVarInsn(ISTORE, SL_TMP2)
        loadCpu(); loadMem(); pushInt(modRM); pushInt(sib); pushInt(disp)
        invokeSupportStatic("readRM32", "(L$CPU_I;L$MEM_I;III)I")
        visitVarInsn(ISTORE, SL_TMP1)
        // result = dst - src
        visitVarInsn(ILOAD, SL_TMP2); visitVarInsn(ILOAD, SL_TMP1); visitInsn(ISUB)
        visitVarInsn(ISTORE, SL_TMP3)
        loadCpu()
        visitVarInsn(ILOAD, SL_TMP3)
        visitVarInsn(ILOAD, SL_TMP2)
        visitVarInsn(ILOAD, SL_TMP1)
        pushInt(0)
        invokeSupportStatic("setArithFlags", "(L$CPU_I;IIIZ)V")
    }

    // ── MethodVisitor extension helpers ──────────────────────────────────────

    private fun MethodVisitor.loadCpu()       = visitVarInsn(ALOAD, SL_CPU)
    private fun MethodVisitor.loadMem()       = visitVarInsn(ALOAD, SL_MEM)
    private fun MethodVisitor.loadInterrupts()= visitVarInsn(ALOAD, SL_INTS)
    private fun MethodVisitor.loadCtx()       = visitVarInsn(ALOAD, SL_CTX)

    private fun MethodVisitor.invokeCpu(name: String, desc: String) =
        visitMethodInsn(INVOKEVIRTUAL, CPU_I, name, desc, false)

    private fun MethodVisitor.invokeMem(name: String, desc: String) =
        visitMethodInsn(INVOKEVIRTUAL, MEM_I, name, desc, false)

    private fun MethodVisitor.invokeSupportStatic(name: String, desc: String) =
        visitMethodInsn(INVOKESTATIC, SUP_I, name, desc, false)

    private fun MethodVisitor.invokeGetEsp() = invokeCpu("getEsp", "()I")
    private fun MethodVisitor.invokeSetEsp() = invokeCpu("setEsp", "(I)V")
    private fun MethodVisitor.invokeGetEflags() = invokeCpu("getEflags", "()I")

    /** Push an int constant using the most compact opcode available. */
    private fun MethodVisitor.pushInt(v: Int) = when (v) {
        -1   -> visitInsn(ICONST_M1)
        0    -> visitInsn(ICONST_0)
        1    -> visitInsn(ICONST_1)
        2    -> visitInsn(ICONST_2)
        3    -> visitInsn(ICONST_3)
        4    -> visitInsn(ICONST_4)
        5    -> visitInsn(ICONST_5)
        in Byte.MIN_VALUE..Byte.MAX_VALUE   -> visitIntInsn(BIPUSH, v)
        in Short.MIN_VALUE..Short.MAX_VALUE -> visitIntInsn(SIPUSH, v)
        else -> visitLdcInsn(v)
    }
}
