package io.github.jwyoon1220.pvm.core.engine

/**
 * Custom [ClassLoader] that exposes [defineClass] so that
 * [JitBlockCompiler] can load ASM-generated bytecode at runtime.
 *
 * The parent loader is set to the loader that loaded [BlockBody] so that the
 * generated class can resolve all PVM types used in method signatures.
 */
internal class JitClassLoader : ClassLoader(BlockBody::class.java.classLoader) {
    fun define(internalName: String, bytes: ByteArray): Class<*> =
        defineClass(internalName.replace('/', '.'), bytes, 0, bytes.size)
}
