package io.github.jwyoon1220.pvm.core.engine

import io.github.jwyoon1220.pvm.api.VmContext
import io.github.jwyoon1220.pvm.core.cpu.CPU
import io.github.jwyoon1220.pvm.core.memory.MemoryBus

/**
 * Static helper methods called by ASM-generated bytecode (INVOKESTATIC).
 *
 * All methods are annotated [@JvmStatic] so they compile to true static
 * methods and can be called without an object receiver from JVM bytecode.
 *
 * Keeping complex logic (EFLAGS, EA computation, r/m32 addressing) here
 * greatly simplifies the generated bytecode while still giving HotSpot a
 * chance to inline and optimise the call sites.
 */
object JitSupport {

    // ── EFLAGS bit masks ────────────────────────────────────────────────────
    private const val ARITH_CLEAR  = -0x8C2   // clears CF, ZF, SF, OF
    private const val INCDEC_CLEAR = -0x8C1   // clears ZF, SF, OF; leaves CF

    // ── Register access ─────────────────────────────────────────────────────

    @JvmStatic fun getReg32(cpu: CPU, reg: Int): Int = when (reg and 7) {
        0 -> cpu.eax; 1 -> cpu.ecx; 2 -> cpu.edx; 3 -> cpu.ebx
        4 -> cpu.esp; 5 -> cpu.ebp; 6 -> cpu.esi; else -> cpu.edi
    }

    @JvmStatic fun setReg32(cpu: CPU, reg: Int, value: Int) { when (reg and 7) {
        0 -> cpu.eax = value; 1 -> cpu.ecx = value; 2 -> cpu.edx = value; 3 -> cpu.ebx = value
        4 -> cpu.esp = value; 5 -> cpu.ebp = value; 6 -> cpu.esi = value; else -> cpu.edi = value
    } }

    @JvmStatic fun getReg8(cpu: CPU, reg: Int): Int = when (reg and 7) {
        0 -> cpu.al; 1 -> cpu.cl; 2 -> cpu.dl; 3 -> cpu.bl
        4 -> cpu.ah; 5 -> cpu.ch; 6 -> cpu.dh; else -> cpu.bh
    }

    @JvmStatic fun setReg8(cpu: CPU, reg: Int, value: Int) { when (reg and 7) {
        0 -> cpu.al = value; 1 -> cpu.cl = value; 2 -> cpu.dl = value; 3 -> cpu.bl = value
        4 -> cpu.ah = value; 5 -> cpu.ch = value; 6 -> cpu.dh = value; else -> cpu.bh = value
    } }

    @JvmStatic fun getReg16(cpu: CPU, reg: Int): Int = when (reg and 7) {
        0 -> cpu.ax; 1 -> cpu.cx; 2 -> cpu.dx; 3 -> cpu.bx
        4 -> cpu.sp; 5 -> cpu.bp; 6 -> cpu.si; else -> cpu.di
    }

    @JvmStatic fun setReg16(cpu: CPU, reg: Int, value: Int) { when (reg and 7) {
        0 -> cpu.ax = value; 1 -> cpu.cx = value; 2 -> cpu.dx = value; 3 -> cpu.bx = value
        4 -> cpu.sp = value; 5 -> cpu.bp = value; 6 -> cpu.si = value; else -> cpu.di = value
    } }

    // ── Effective address ────────────────────────────────────────────────────

    /**
     * Computes the effective address for a ModRM+SIB+disp combination.
     * [sib] must be -1 when there is no SIB byte (i.e., rm != 4).
     */
    @JvmStatic fun computeEa(cpu: CPU, modRM: Int, sib: Int, disp: Int): Int {
        val mod = (modRM shr 6) and 3
        val rm  = modRM and 7
        if (rm == 4) {
            val scale  = 1 shl ((sib shr 6) and 3)
            val idx    = (sib shr 3) and 7
            val base   = sib and 7
            val idxVal = if (idx == 4) 0 else getReg32(cpu, idx)
            val baseVal = if (base == 5 && mod == 0) 0 else getReg32(cpu, base)
            return baseVal + idxVal * scale + disp
        }
        val baseVal = if (rm == 5 && mod == 0) 0 else getReg32(cpu, rm)
        return baseVal + disp
    }

    // ── r/m32 read / write ───────────────────────────────────────────────────

    @JvmStatic fun readRM32(cpu: CPU, memory: MemoryBus, modRM: Int, sib: Int, disp: Int): Int {
        val mod = (modRM shr 6) and 3
        val rm  = modRM and 7
        return if (mod == 3) getReg32(cpu, rm)
               else memory.read32(computeEa(cpu, modRM, sib, disp))
    }

    @JvmStatic fun writeRM32(cpu: CPU, memory: MemoryBus, modRM: Int, sib: Int, disp: Int, value: Int) {
        val mod = (modRM shr 6) and 3
        val rm  = modRM and 7
        if (mod == 3) setReg32(cpu, rm, value)
        else memory.write32(computeEa(cpu, modRM, sib, disp), value)
    }

    // ── EFLAGS setters ───────────────────────────────────────────────────────

    @JvmStatic fun setArithFlags(cpu: CPU, result: Int, a: Int, b: Int, add: Boolean) {
        val cf: Int; val of: Int
        if (add) {
            cf = ((a.toLong() and 0xFFFFFFFFL) + (b.toLong() and 0xFFFFFFFFL) ushr 32).toInt() and 1
            of = (((a xor result) and (b xor result)) ushr 31) and 1
        } else {
            cf = if (Integer.compareUnsigned(a, b) < 0) 1 else 0
            of = (((a xor b) and (a xor result)) ushr 31) and 1
        }
        val zf = if (result == 0) 1 else 0
        val sf = (result ushr 31) and 1
        cpu.eflags = (cpu.eflags and ARITH_CLEAR) or cf or (zf shl 6) or (sf shl 7) or (of shl 11)
    }

    @JvmStatic fun setIncDecFlags(cpu: CPU, result: Int, old: Int, inc: Boolean) {
        val of = if (inc) (((old xor result) and (1 xor result)) ushr 31) and 1
                 else    (((old xor 1) and (old xor result)) ushr 31) and 1
        val zf = if (result == 0) 1 else 0
        val sf = (result ushr 31) and 1
        cpu.eflags = (cpu.eflags and INCDEC_CLEAR) or (zf shl 6) or (sf shl 7) or (of shl 11)
    }

    // ── Group 1 helper (0x81 / 0x83) ────────────────────────────────────────

    @JvmStatic fun grp1Rm32Imm(
        cpu: CPU, memory: MemoryBus, modRM: Int, sib: Int, disp: Int, imm: Int
    ) {
        val reg = (modRM shr 3) and 7
        val src = readRM32(cpu, memory, modRM, sib, disp)
        when (reg) {
            0 -> { val r = src + imm; setArithFlags(cpu, r, src, imm, true);  writeRM32(cpu, memory, modRM, sib, disp, r) }
            5 -> { val r = src - imm; setArithFlags(cpu, r, src, imm, false); writeRM32(cpu, memory, modRM, sib, disp, r) }
            7 -> setArithFlags(cpu, src - imm, src, imm, false)
            else -> throw UnsupportedOperationException("Grp1 /reg=$reg not implemented")
        }
    }

    // ── JCC condition evaluator ──────────────────────────────────────────────

    @JvmStatic fun jccTaken(opcode: Int, eflags: Int): Boolean {
        val cf = eflags and 1
        val zf = (eflags shr 6) and 1
        val sf = (eflags shr 7) and 1
        val pf = (eflags shr 2) and 1
        val of = (eflags shr 11) and 1
        return when (opcode) {
            0x70 -> of == 1;  0x71 -> of == 0
            0x72 -> cf == 1;  0x73 -> cf == 0
            0x74 -> zf == 1;  0x75 -> zf == 0
            0x76 -> cf == 1 || zf == 1;  0x77 -> cf == 0 && zf == 0
            0x78 -> sf == 1;  0x79 -> sf == 0
            0x7A -> pf == 1;  0x7B -> pf == 0
            0x7C -> sf != of; 0x7D -> sf == of
            0x7E -> zf == 1 || sf != of
            else -> zf == 0 && sf == of  // 0x7F JG
        }
    }

    // ── Interrupt dispatch ───────────────────────────────────────────────────

    @JvmStatic fun dispatchInterrupt(
        cpu: CPU,
        interrupts: io.github.jwyoon1220.pvm.core.io.InterruptService,
        vmContext: VmContext,
        vector: Int
    ) = interrupts.dispatch(vector, vmContext)
}
